### ISSUE TITLE
Caret position fail when font-size different than 12px

### ISSUE THREAD

**Issue by seballot** [ether/ep_cursortrace#15]
Hello,
Thanks for this plugin, it's great !

When I change the font-size of the pad (I use 14px instead of 12px) the caret is broken. It is working on the beginning of the line, but more we are writing, more the caret have an offset from the real position

![image](https://user-images.githubusercontent.com/17404254/46583128-fff1d280-ca51-11e8-8a39-6eccf9ac2454.png)

![image](https://user-images.githubusercontent.com/17404254/46583131-0ed88500-ca52-11e8-88f2-c925dff7af0f.png)

**Comment by JohnMcLear** [comment]
I think this is fixed now if you wanna test and lemme know :)

**Comment by bonnebulle** [comment]
Sadly I have the same issue 
I try multiple fonts and line-spacing.

Version d’Etherpad
Numéro de version: 1.9.0
Dernière version disponible: 1.8.18
Git sha: [48381de](https://github.com/ether/etherpad-lite/commit/48381de)

If you have a clue...
Thanks for your work and time
