### ISSUE TITLE
Does this work for read only pads?

### ISSUE THREAD

**Issue by mir123** [ether/ep_cursortrace#16]
I would like to have the caret be shown on a read only pad. I can't see the cursorPosition message being received on the read only pad. Is there any way to receive it?

**Comment by JohnMcLear** [comment]
Do handlecustom messages get sent to read-only pad sockets?  I don't know

**Comment by mir123** [comment]
So it turns out I was using the npm version, which is older. This one in GitHub works ok, though it deserves some maintenance.
